### ISSUE TITLE
explore other (non-doc.write) dom ready solutions

### ISSUE THREAD

**Issue by paulirish** [keithclark/selectivizr#3] opened 2011-01-31 18:38 UTC
this old dean edwards snippet was used in jquery but was removed due to edge case incompatibilities.

the doScroll basic check from diego perini (called IEContentLoaded) is much safer.

**Comment by keithclark** [comment] 2011-01-31 18:50
I agree, document.write isn't the best way to watch for DOM ready events.

Originally, I used Diego's doScroll() trick but it failed if selectivizr was used in any content loaded into an iframe, so I had to revert back to Dean Edwards technique as it was causing issues for some users.

I'm open to suggestions.

**Comment by paulirish** [comment] 2011-01-31 19:15
Ah interesting.  I'll tweak the issue title.

**Comment by ZeeAgency** [comment] 2011-02-02 09:53
https://github.com/keithclark/selectivizr/pull/6

**Comment by keithclark** [comment] 2011-02-10 15:38
Diego has been in touch.

I have a new version of his DOMContentLoaded script to test :)

**Comment by keithclark** [comment] 2011-02-20 23:48
Closing this issue as it's become a dupe of issue #4

**Closed as completed by keithclark** 2011-02-20 23:48 UTC
